@startuml Deployment
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' src: https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4CoreDiagrams.md
' src: https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4_Deployment%20Diagram%20Sample%20-%20bigbankplc.puml

' Deployment_Node(alias, label, ?type, ?descr, ?sprite, ?tags, ?link)
' Node(alias, label, ?type, ?descr, ?sprite, ?tags, ?link): short name of Deployment_Node()
' Node_L(alias, label, ?type, ?descr, ?sprite, ?tags, ?link): left aligned Node()
' Node_R(alias, label, ?type, ?descr, ?sprite, ?tags, ?link): right aligned Node()

AddElementTag("fallback", $bgColor="#c0c0c0")
AddRelTag("fallback", $textColor="#c0c0c0", $lineColor="#438DD5")

title Deployment Diagram for Lounastutka

Deployment_Node(webApp, "Lounastutka Web Application", "Hetzner VPS"){
    Deployment_Node(beHW, "Backend", ""){
        Deployment_Node(beSW, "", ""){
            Container(beCont, "", "", "")
        }
    }
    Deployment_Node(dbHW, "Application Content Database", "PostgreSQL"){
        Deployment_Node(dbSW, "ServiceName", "Hardware"){
            ContainerDb(dbCont, "Database", "Relational Database Schema", "Stores user registration information, credentials, restaurant information.")
        }
    }
    
    Deployment_Node(appHW, "Label", "Hardware"){
        Deployment_Node(appSW, "Software", ""){
            Container(web, "", "", "")
        }
    }
}

Deployment_Node(pc, "Customer's device", "Mobile device or Personal Computer"){
    Deployment_Node(browser, "Web Browser", "Chromium, Mozilla Firefox, Apple Safari, Microsoft Edge"){
        Container(spa, "Single Page Application", "JS, TS, and React", "Provides customers with mapview of the restaurants and their menus on web browser.")
    }
}

' Rel(pc, api, "Makes API calls to", "json/HTTPS")
' Rel(spa, api, "Makes API calls to", "json/HTTPS")
' Rel_U(web, spa, "Delivers to the customer's web browser")
' Rel(api, db, "Reads from and writes to", "JDBC")
' Rel(api, db2, "Reads from and writes to", "JDBC", $tags="fallback")
' Rel_R(db, db2, "Replicates data to")



SHOW_LEGEND()


@enduml
