site_name: Lounastutka Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Frontend: frontend/index.md
  - Backend: backend/index.md
  - Database: database/index.md
  - Architecture: 
    - Description: architecture/index.md
    - Microservice: architecture/microservice.md
    - Deployment: architecture/deployment.md
    - Data flow: architecture/dataflow.md
    - Use-case: architecture/usecase.md
  - Environment:
    - Docker: environment/docker.md
    - Hetzner: environment/hetzner.md
    - GitHub Actions: environment/github-actions.md
    - Nginx: environment/nginx.md

watch:
  - mkdocs.yml
  - Backend/README.md
  - Frontend/README.md
  - Database/README.md
  - docs/

theme: readthedocs

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

