// NOTE:
// This file should contain the database table formats and types so they can be more easily identified (with their types) in other files where needed and can be imported as needed
import type {
  AuthenticatorTransportFuture,
  CredentialDeviceType,
  Base64URLString,
} from '@simplewebauthn/server';

// NOTE: Should match the users table format in PostGreSQL
// NOTE: Use "snake_case" for column names in postgreSQL tables
export type UserModel = {
  id: any; // PostgreSQL handled SERIAL PRIMARY KEY 
  email: string; // UNIQUE NOT NULL
  passwordHash?: string | null; // Posgre TEXT
  creationDate: Date; // TIMESTAMP (DEFAULT NOW()?) (given by user or generated by backend / postgre ?)
};

// NOTE: The following is taken from here: https://simplewebauthn.dev/docs/packages/server#additional-data-structures
/**
 * It is strongly advised that credentials get their own DB
 * table, ideally with a foreign key somewhere connecting it
 * to a specific UserModel.
 *
 * "SQL" tags below are suggestions for column data types and
 * how best to store data received during registration for use
 * in subsequent authentications.
 */
// NOTE: use snake_case for column names in postgreSQL tables
export type PasskeyModel = {
  // SQL: Store as `TEXT`. Index this column
  id: Base64URLString;
  // SQL: Store raw bytes as `BYTEA`/`BLOB`/etc...
  //      Caution: Node ORM's may map this to a Buffer on retrieval,
  //      convert to Uint8Array as necessary
  publicKey: Uint8Array;
  // SQL: Foreign Key to an instance of your internal user model 
  // INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
  user: UserModel;
  // SQL: Store as `TEXT`. Index this column. A UNIQUE constraint on
  //      (webAuthnUserID + user) also achieves maximum user privacy
  //      NOTE: not used as no passwordless is supported
  // webauthnUserID: Base64URLString;

  // SQL: Consider `BIGINT` since some authenticators return atomic timestamps as counters
  counter: number;
  // SQL: `VARCHAR(32)` or similar, longest possible value is currently 12 characters
  // Ex: 'singleDevice' | 'multiDevice'
  deviceType: CredentialDeviceType;
  // SQL: `BOOL` or whatever similar type is supported
  backedUp: boolean;
  // SQL: `VARCHAR(255)` and store string array as a CSV string
  // Ex: ['ble' | 'cable' | 'hybrid' | 'internal' | 'nfc' | 'smart-card' | 'usb']
  transports?: AuthenticatorTransportFuture[];
};

export type RestaurantModel = {
  id?: number;
  name: string;
  address?: string;
  lat?: number;
  lon?: number;
  category?: string;
  description?: string;
  phone?: string;
  website?: string;
  priceLevel?: string;
  stars?: number;
  reviews?: number;
};

export type MenuModel = {
  id?: number;
  restaurantId: number;
  date?: Date;
};

export type MenuItemModel = {
  id?: number;
  menuId: number;
  name: string;
};

// The return type for getting all restaurant menu data.
export type RawMenuDataModel = {
  id: number;
  restaurantId: number;
  menuId: number;
  name: string;
};
